export const coreNodeTypes = [
  'input',
  'note',
  'group',
  'custom',
  'last-user-input',
  'last-rp-output',
  'event-manager',
  'history',
  'memory-slot',
  'phone-message-router',
  'text-selector',
  'llm-prompt-switch',
  'decision-router',
  'fixed-number',
  'fixed-bool',
  'settings-value',
  'context-compression',
  'load-text',
  'write-text',
  'text-preview',
  'context-builder',
  'llm-decision',
  'llm-prompt',
  'combiner',
  'text-replace',
  'format-repair',
  'character-stats',
  'output',
  'rp-storybook',
  'rp-storybook-editor',
  'phone-apps',
] as const;

export type CoreNodeType = typeof coreNodeTypes[number];
