/** Dotted-path core token keys, grouped by category. Extend this list as new
 * categories/tokens get consumed by CSS during this or future migrations.
 * Unknown/custom keys authored in a theme.json are still legal and get
 * flattened into CSS custom properties — this list only drives IDE
 * autocomplete and the "every core token resolves" regression test. */
export const CORE_TOKEN_KEYS = [
  // color (semantic, shadcn-style)
  'color.background',
  'color.backgroundElevated',
  'color.header',
  'color.surfaceRail',
  'color.surfaceContent',
  'color.panel',
  'color.card',
  'color.cardStrong',
  'color.input',
  'color.foreground',
  'color.mutedForeground',
  'color.primary',
  'color.primaryForeground',
  'color.secondary',
  'color.border',
  'color.borderSoft',
  'color.userBubble',
  'color.userBubbleBorder',
  'color.rail',
  'color.complete',
  'color.phoneGlass',
  // graph mode
  'graph.background',
  'graph.chrome',
  'graph.panel',
  'graph.panel2',
  'graph.line',
  'graph.lineSoft',
  'graph.text',
  'graph.muted',
  'graph.faint',
  'graph.accent',
  'graph.accentSoft',
  'graph.success',
  'graph.violet',
  // storybook editor
  'storybook.background',
  'storybook.panel',
  'storybook.passive',
  'storybook.line',
  'storybook.lineSoft',
  'storybook.text',
  'storybook.muted',
  'storybook.faint',
  'storybook.accent',
  'storybook.accentSoft',
  'storybook.violet',
  'storybook.violetSoft',
  'storybook.pink',
  'storybook.lime',
  // studio shell chrome (play-mode composer/rail/tabs that don't fit an
  // existing semantic color slot -- see studio-shell.css)
  'shell.chatSurface',
  'shell.messageBorder',
  'shell.messageText',
  'shell.labelStrong',
  'shell.inputBorder',
  'shell.segmentedBg',
  'shell.iconColor',
  'shell.iconButtonBg',
  'shell.autoTurnText',
  'shell.railBorder',
  'shell.characterStripBg',
  'shell.railActiveColor',
  'shell.railActiveBorder',
  'shell.railActiveBg',
  'shell.badgeBorder',
  'shell.badgeText',
  'shell.badgeBg',
  'shell.badgeGlow',
  'shell.tabBorder',
  'shell.tabBorderBottom',
  'shell.tabText',
  'shell.tabBg',
  'shell.tabActiveBorder',
  'shell.tabActiveBg',
  'shell.tabActiveText',
  'shell.tabSubtext',
  'shell.topbarButtonBorder',
  'shell.topbarButtonText',
  'shell.topbarButtonBg',
  'shell.topbarHoverBg',
  'shell.topbarHoverBorder',
  'shell.badgeAccentBg',
  'shell.topbarContextBorder',
  'shell.topbarMutedText',
  'shell.topbarSelectBg',
  // upstream's own global palette (:root in src/styles.css, predates the
  // theme system) -- aliased on .studio so the ~400 existing var(--accent)/
  // var(--surface)/etc. references throughout styles.css pick up the
  // active theme without editing each of those rules individually
  'app.accent',
  'app.accentLight',
  'app.surface',
  'app.surfaceAlt',
  'app.surfaceSoft',
  'app.line',
  'app.muted',
  'app.cyan',
  'app.wire',
  'app.success',
  'app.successSoft',
  'app.warning',
  'app.warningSoft',
  'app.danger',
  'app.dangerSoft',
  'app.softWhite',
  // The single most-repeated pattern in src/styles.css: 28+ modal dialogs
  // (Options, Providers/connection, Files, System Log, password prompt,
  // LLM run report, voice playback, ...) all share this exact
  // border/background/text triple. One derived slot here fixes every one
  // of them at once instead of hand-remapping each dialog separately.
  'app.dialogBg',
  'app.dialogBorder',
  'app.dialogText',
  'app.text',
  // Auto-extracted from src/styles.css: every color literal reused 5+ times
  // that didn't already correspond to a semantic token above. Named from
  // the literal's own characters (not hand-picked semantic names) since
  // these were generated by scripts/extract-raw-theme-tokens.mjs rather
  // than curated by hand -- optional tier, never guaranteed, since every
  // consuming declaration already carries the original literal as its CSS
  // fallback (var(--theme-raw-x, original-literal)). A theme only needs to
  // set the ones it actually wants to override; everything else keeps
  // rendering the original color untouched.
  'raw.vedf1ff',
  'raw.vrgba255255255008',
  'raw.v232d42',
  'raw.v303a4e',
  'raw.v1e293b',
  'raw.v111722',
  'raw.v8794b1',
  'raw.vrgba000055',
  'raw.v94a3b8',
  'raw.v7eb9c5',
  'raw.v0f141f',
  'raw.vrgba000028',
  'raw.vrgba00002',
  'raw.vrgba255255255005',
  'raw.v7d8ba6',
  'raw.v64748b',
  'raw.vrgba255255255004',
  'raw.vcbd5e1',
  'raw.vrgba255255255006',
  'raw.veff2ff',
  'raw.vdfe7ff',
  'raw.v2a374e',
  'raw.vdbe4f7',
  'raw.v090d14',
  'raw.vrgba255255255003',
  'raw.vrgba25525525501',
  'raw.vrgba000022',
  'raw.v21293a',
  'raw.v101722',
  'raw.vrgba138115201028',
  'raw.vrgba000025',
  'raw.v0c111a',
  'raw.vrgba000042',
  'raw.vf5b96b',
  'raw.v151d2d',
  'raw.v263248',
  'raw.vrgba13811520101',
  'raw.vrgba138115201025',
  'raw.v2a3447',
  'raw.vrgba255255255002',
  'raw.v263247',
  'raw.v8999b3',
  'raw.vrgba126185197055',
  'raw.vedf2ff',
  'raw.vrgba255255255007',
  'raw.vrgba138115201012',
  'raw.ve2e8f0',
  'raw.v35445e',
  'raw.v293449',
  'raw.v111826',
  'raw.v2b3447',
  'raw.v384152',
  'raw.v242e40',
  'raw.vrgba000012',
  'raw.v38bdf8',
  'raw.vrgba000035',
  'raw.vrgba138115201022',
  'raw.v0d1420',
  'raw.vrgba138115201035',
  'raw.vrgba138115201015',
  'raw.vrgba00003',
  'raw.v142235',
  'raw.v131b28',
  'raw.vrgba138115201024',
  'raw.v8fa2c1',
  'raw.vdbeafe',
  'raw.vrgba000034',
  'raw.vrgba000038',
  'raw.vff7b86',
  'raw.vf2f5ff',
  'raw.v323947',
  'raw.v0c121c',
  'raw.v273246',
  'raw.v243149',
  'raw.v111827',
  'raw.vrgba00004',
  'raw.vrgba000015',
  'raw.vrgba13811520102',
  'raw.v715da7',
  'raw.vrgba25525525502',
  'raw.ve7eefc',
  'raw.v253047',
  'raw.vf4f7ff',
  'raw.v233147',
  'raw.v111a28',
  'raw.vff9aa4',
  'raw.v2c374d',
  'raw.v78e6a3',
  // Auto-extracted from graph-workbench.css: decorative/status accents
  // (error red, success green glows, glassy overlays) deliberately left
  // un-derived, same reasoning as app.warning/app.danger above -- a fixed
  // status color across themes is a reasonable, common choice. The
  // structural panel/border/text colors in that file were instead mapped
  // onto the existing graph.* namespace (see graph-workbench.css directly).
  'raw.v354061',
  'raw.v56d99a',
  'raw.vb8c5ed',
  'raw.vcbd7fa',
  'raw.vd9e6f8',
  'raw.vdce8ff',
  'raw.vfecaca',
  'raw.vrgba119134176017',
  'raw.vrgba11913417602',
  'raw.vrgba119134176026',
  'raw.vrgba121215239004',
  'raw.vrgba121215239025',
  'raw.vrgba125211252032',
  'raw.vrgba125211252035',
  'raw.vrgba125211252068',
  'raw.vrgba125211252072',
  'raw.vrgba127292902',
  'raw.vrgba1272929024',
  'raw.vrgba164236104008',
  'raw.vrgba164236104034',
  'raw.vrgba164236104065',
  'raw.vrgba248113113045',
  'raw.vrgba248113113048',
  'raw.vrgba2552552550018',
  'raw.vrgba2552552550035',
  'raw.vrgba255255255004',
  'raw.vrgba255255255008',
  'raw.vrgba25525525501',
  'raw.vrgba86217154015',
  'raw.vrgba8621715402',
  // Auto-extracted from storybook-editor.css, same reasoning as above --
  // decorative/status accents and rare one-off overlays left un-derived;
  // structural panel/text colors were mapped onto the storybook.*
  // namespace directly in storybook-editor.css.
  'raw.v060a12',
  'raw.v061018',
  'raw.v070b14',
  'raw.v080d18',
  'raw.v0a101b',
  'raw.v222946',
  'raw.v33405f',
  'raw.v34405e',
  'raw.v394563',
  'raw.v424c68',
  'raw.v43506f',
  'raw.v455370',
  'raw.v5e315e',
  'raw.vb9c7e4',
  'raw.vc6d2ee',
  'raw.vdbe7ff',
  'raw.ve4edff',
  'raw.veef8ff',
  'raw.vf1f7ff',
  'raw.vffd8f4',
  'raw.vrgba000028',
  'raw.vrgba12121523901',
  'raw.vrgba121215239012',
  'raw.vrgba12121523905',
  'raw.vrgba121215239052',
  'raw.vrgba12121523906',
  'raw.vrgba121215239065',
  'raw.vrgba130148190018',
  'raw.vrgba130148190022',
  'raw.vrgba131832094',
  'raw.vrgba131832098',
  'raw.vrgba162119255008',
  'raw.vrgba162119255012',
  'raw.vrgba162119255016',
  'raw.vrgba162119255018',
  'raw.vrgba162119255022',
  'raw.vrgba162119255032',
  'raw.vrgba162119255056',
  'raw.vrgba16211925506',
  'raw.vrgba162119255062',
  'raw.vrgba16211925507',
  'raw.vrgba167235114008',
  'raw.vrgba167235114034',
  'raw.vrgba167235114062',
  'raw.vrgba172237078',
  'raw.vrgba172237088',
  'raw.vrgba182338092',
  'raw.vrgba182539096',
  'raw.vrgba212843088',
  'raw.vrgba24110619601',
  'raw.vrgba241106196012',
  'raw.vrgba241106196042',
  'raw.vrgba241106196044',
  'raw.vrgba241106196058',
  'raw.vrgba255255255022',
  'raw.vrgba255255255034',
  'raw.vrgba5814072',
  'raw.vrgba81119082',
  'raw.vrgba91120055',
  'raw.vrgba9112009',
  // Auto-extracted from phone-device.css and roleplay-dual-pane.css: the
  // physical device bezel/casing (.roleplay-phone-device, -status, -home)
  // is chrome, not handcrafted content, so it's in scope -- but it's
  // deliberately left un-derived (like the other raw.* tokens) so the
  // realistic metal/glass phone-casing look doesn't shift with the studio
  // theme by default. Still technically overridable by a theme.json that
  // wants to restyle it.
  'raw.v000',
  'raw.v020203',
  'raw.v030304',
  'raw.v050506',
  'raw.v070708',
  'raw.v0b0b0d',
  'raw.v0b0b0e',
  'raw.v111116',
  'raw.v171821',
  'raw.v1d1e22',
  'raw.v1e1f24',
  'raw.v202126',
  'raw.v2b2d32',
  'raw.v3c3d42',
  'raw.vfff',
  'raw.vrgba000048',
  'raw.vrgba000052',
  'raw.vrgba000072',
  'raw.vrgba000082',
  'raw.vrgba13013214007',
  'raw.vrgba191219254048',
  'raw.vrgba2552552550045',
  'raw.vrgba2552552550075',
  'raw.vrgba255255255012',
  'raw.vrgba255255255013',
  'raw.vrgba255255255016',
  'raw.vrgba255255255018',
  'raw.vrgba25525525509',
  'raw.vrgba283554095',
  // Auto-extracted from account-links.css, characterAssistant.css,
  // characterRelationships.css, and the non-excluded (.character-account-*)
  // portion of characterAppProfiles.css -- status/decorative accents left
  // un-derived for the same reason as elsewhere.
  'raw.v0006',
  'raw.v8995aa',
  'raw.v91b79a',
  'raw.v91c29c',
  'raw.v9ae0bd',
  'raw.vaeb9ce',
  'raw.vc88c96',
  'raw.vdbe2f4',
  'raw.vf1a4ad',
  'raw.vf1c46b',
  'raw.vffffff30',
  'raw.vrgba108211173014',
  'raw.vrgba117181132038',
  'raw.vrgba126556701',
  'raw.vrgba197112124028',
  'raw.vrgba241196107013',
  'raw.vrgba7412686014',
  'raw.vrgba9132004',
  // typography
  'typography.headingFont',
  'typography.bodyFont',
  'typography.fontWeight',
  'typography.fontWeightHeading',
  'typography.letterSpacing',
  'typography.textTransform',
  'typography.baseSize',
  'typography.lineHeight',
  // shape
  'shape.radius',
  'shape.radiusCard',
  'shape.radiusButton',
  'shape.radiusInput',
  'shape.borderWidth',
  'shape.borderStyle',
  'shape.clipPath',
  // effect
  'effect.cardShadow',
  'effect.buttonShadow',
  'effect.buttonShadowHover',
  'effect.accentGlow',
  'effect.backgroundTexture',
  'effect.buttonBackground',
  // motion
  'motion.transitionDuration',
  'motion.transitionEasing',
  'motion.hoverScale',
] as const;

export type CoreTokenKey = (typeof CORE_TOKEN_KEYS)[number];

/** The subset of core tokens that must always resolve to *some* value: they
 * have no CSS-level `var(x, fallback)` in the consuming stylesheet (or their
 * only sensible fallback would itself be a per-theme value), so the resolver
 * force-backfills them from the `base` theme when nothing else provides one.
 *
 * Every other core token is intentionally left unset when neither the
 * `extends` chain nor basic-tier derivation supplies a value — the
 * consuming CSS already carries its own fallback (e.g.
 * `var(--theme-radius-card, var(--theme-radius))`), and force-backfilling
 * it from `base` would defeat that per-theme fallback (every theme would
 * silently get base's own radius instead of its own). */
export const GUARANTEED_TOKEN_KEYS = [
  'color.background', 'color.backgroundElevated', 'color.header',
  'color.surfaceRail', 'color.surfaceContent', 'color.panel', 'color.card', 'color.cardStrong',
  'color.input', 'color.foreground', 'color.mutedForeground',
  'color.primary', 'color.primaryForeground', 'color.secondary',
  'color.border', 'color.borderSoft',
  'color.userBubble', 'color.userBubbleBorder',
  'color.rail', 'color.complete', 'color.phoneGlass',
  // graph.*/storybook.*/app.* are NOT guaranteed: they're always derived
  // from the color.* tokens above (see DERIVATION_RULES in
  // themeResolver.ts), which are guaranteed. Giving them their own value in
  // base.json's tokens tree would re-trigger gotcha #1 -- base's tokens
  // merge into every theme's chain before derivation ever runs, so an
  // explicit base value would permanently pre-empt derivation for every
  // theme, exactly the bug this split is designed to prevent.
  'shell.chatSurface', 'shell.messageBorder', 'shell.messageText', 'shell.labelStrong',
  'shell.inputBorder', 'shell.segmentedBg', 'shell.iconColor', 'shell.iconButtonBg',
  'shell.autoTurnText', 'shell.railBorder', 'shell.characterStripBg',
  'shell.railActiveColor', 'shell.railActiveBorder', 'shell.railActiveBg',
  'shell.badgeBorder', 'shell.badgeText', 'shell.badgeBg', 'shell.badgeGlow',
  'shell.tabBorder', 'shell.tabBorderBottom', 'shell.tabText', 'shell.tabBg',
  'shell.tabActiveBorder', 'shell.tabActiveBg', 'shell.tabActiveText', 'shell.tabSubtext',
  'shell.topbarButtonBorder', 'shell.topbarButtonText', 'shell.topbarButtonBg',
  'shell.topbarHoverBg', 'shell.topbarHoverBorder', 'shell.badgeAccentBg',
  'shell.topbarContextBorder', 'shell.topbarMutedText', 'shell.topbarSelectBg',
  'typography.fontWeight',
  'shape.radius',
] as const satisfies readonly CoreTokenKey[];

/** Nested dotted-object JSON shape theme authors write; leaves are raw CSS
 * value strings (a color, a full box-shadow, a full clip-path polygon) —
 * no {value, unit} tagged objects, so exotic themes can hold complete CSS
 * expressions (gradients, clip-paths) in a single token. */
export type ThemeTokenTree = { [key: string]: string | ThemeTokenTree | undefined };

/** Open dictionary: any dotted key is legal; known CORE keys get
 * autocompletion + type-checked values, unknown ones still type-check
 * (open-world model — required so future file-by-file CSS migrations can
 * introduce new token names without changing this file). */
type CoreTokens = Partial<Record<CoreTokenKey, string>>;
type ThemeTokenDictionary = CoreTokens & Record<string, string | ThemeTokenTree | undefined>;

/** The small set of knobs the theme picker/editor exposes via simple
 * pickers. When an advanced token is unset, the resolver derives a sensible
 * value from these before falling back to the base theme. */
type ThemeBasicTokens = {
  primary?: string;
  secondary?: string;
  background?: string;
  foreground?: string;
  headingFont?: string;
  bodyFont?: string;
  radius?: string;
};

export interface ThemeManifest {
  /** Folder name / stable identifier, e.g. "iphone-noir". */
  id: string;
  label: string;
  /** Parent theme id. Defaults to "base" when omitted, except for "base" itself. */
  extends?: string;
  /** True only for "base" — excluded from the theme picker. */
  hidden?: boolean;
  /** Picker display order, ascending. Themes without one sort after themes
   * that have one, alphabetically among themselves. */
  order?: number;
  basic?: ThemeBasicTokens;
  /** Nested-dotted "advanced" tier; always wins over a derived value. */
  tokens?: ThemeTokenDictionary;
  /** Where this manifest was discovered: a bundled preset that ships with
   * the app (read-only), or a user-authored theme dropped into the
   * per-user themes folder. Set by the loader, not authored in the JSON
   * file itself — a hand-authored theme.json never needs this field. */
  source?: 'bundled' | 'user';
}

/** Fully flattened, resolved output — every value is a plain string ready
 * for `element.style.setProperty`, keyed by the hyphenated CSS custom
 * property name. */
export type ResolvedThemeTokens = Record<string, string>;

export const RESERVED_BASE_THEME_ID = 'base';
